id: P009216
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2413
  title: སྣར་ཐང་ཆོས་སྡེའི་ལོ་རྒྱུས
  author: ''
  volumes:
    72397eae195349c591ec795226a3de71:
      image_group_id: I1CZ2464
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
